Fix MSVC error about missing std::bit_cast
Without this change, I was getting the following error from MSVC:
```
D:\a\Sleipnir\Sleipnir\build\_deps\eigen3-src\Eigen\src\Core\NumTraits.h(103,27): error C3878: syntax error: unexpected token '>' following 'simple-type-specifier' [D:\a\Sleipnir\Sleipnir\build\Sleipnir.vcxproj]
  (compiling source file '../src/autodiff/variable_matrix.cpp')
      D:\a\Sleipnir\Sleipnir\build\_deps\eigen3-src\Eigen\src\Core\NumTraits.h(103,27):
      missing one of: '(' '{' ?
```