Update Assign_MKL.h to cast disparate enum type to int, so it can be compared to a different enum type, resolving issue #1808.
Comparison of different enums was deprecated in C++20 and is fully removed in C++26. So compiling in "latest" mode, this is now an error rather than a warning that can be suppressed. clangcl 18 gives this error message:
{src}/eigen\Eigen\src/Core/Assign_MKL.h(135,1): error : invalid comparison of different enumeration types ('Eigen::internal::vml_assign_traits<Eigen::Matrix<double, 1, -1>, const Eigen::ArrayWrapper<Eigen::Matrix<double, 1, -1>>>::(unnamed enum at {src}/eigen\Eigen\src\Core\Assign_MKL.h:63:5)' and 'Eigen::TraversalType')
{src}/eigen\Eigen\src/Core/Assign_MKL.h(109,3): message : expanded from macro 'EIGEN_MKL_VML_DECLARE_UNARY_CALLS_REAL'
{src}/eigen\Eigen\src/Core/Assign_MKL.h(90,63): message : expanded from macro 'EIGEN_MKL_VML_DECLARE_UNARY_CALL'

The simple cast of LinearTraversal to int resolves this problem.