Fix unused local typedef warning in matrix exponential
```
/Users/runner/work/Sleipnir/Sleipnir/build/_deps/eigen3-src/unsupported/Eigen/src/MatrixFunctions/MatrixExponential.h:287:11: error: unused type alias 'Scalar' [-Werror,-Wunused-local-typedef]
  287 |     using Scalar = typename traits<MatrixType>::Scalar;
      |           ^
```